kind: pipeline
type: ssh
name: Teste de Conexao SSH - Sem Plataforma

node:
  environment: ssh-build
  arch: arm64

server:
  host: build-server-node
  user: root
  ssh_key:
    from_secret: BUILD_SERVER_SSH_KEY

workspace:
  path: /root/test_workspace

trigger:
  event: [push]

steps:
  - name: Validar Conexao e Ambiente
    commands:
      - echo ">>>>>> CONEXÃO SSH BEM-SUCEDIDA! <<<<<<"
      - whoami
      - pwd
      - ls -la
