kind: pipeline
type: ssh
name: CI + push + Deploy Homologação

# A seção 'node' não é mais necessária, pois o runner SSH não usa labels
# para selecionar o servidor, ele usa a diretiva 'server'..
node:
   environment: ssh-build
   arch: arm64

trigger:
  event:
    - push
    - pull_request
    - tag

# mesma config de server.
server:
  host: build-server-node
  user: root
  ssh_key:
    from_secret: BUILD_SERVER_SSH_KEY

steps:
  # ...mesmos steps de setup, lint, testes, sonar...
  - name: Setup do Projeto
    commands:
      - npm ci
      - mkdir -p reports coverage

  - name: Verificação de Lint
    commands:
      - npm run lint:report

  - name: Testes Unitários com Cobertura
    commands:
      - npm test -- --coverage

  - name: Análise e Validação do SonarQube
    environment:
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SONAR_HOST_URL:
        from_secret: SONAR_HOST_URL
    commands:
      - set -e
      - npx sonar-scanner -Dsonar.token=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL
    when:
      event:
        - push
        - pull_request
        - tag

  - name: Validar Quality Gate
    environment:
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SONAR_HOST_URL:
        from_secret: SONAR_HOST_URL
    commands:
      - set -e
      - |
        echo "Aguardando processamento da análise no SonarQube...."
        sleep 10
        taskId=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/project_analyses/search?project=calculadora-api" | jq -r '.current.component.analysisId')
        echo "Último taskId: $taskId"
        status=""
        tentativas=0
        while [ "$status" != "SUCCESS" ] && [ $tentativas -lt 10 ]; do
          sleep 5
          status=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/ce/task?id=$taskId" | jq -r '.task.status')
          echo "Status: $status"
          tentativas=$((tentativas+1))
        done
        qualityStatus=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=calculadora-api" | jq -r '.projectStatus.status')
        echo "Resultado do Quality Gate: $qualityStatus"
        if [ "$qualityStatus" != "OK" ]; then
          echo "❌ Quality Gate falhou. Bloqueando deploy."
          exit 1
        else
          echo "✅ Quality Gate aprovado. Continuando pipeline."
        fi
    when:
      event:
        - push
        - pull_request
        - tag

  # Nova etapa: Security Scan
  - name: Security Scan
    commands:
      - |
        # Executa o scan do código fonte e dependências
        trivy fs --severity HIGH,CRITICAL --exit-code 1 --no-progress . > trivy-report.txt
        
        # Verifica se encontrou vulnerabilidades
        if [ $? -ne 0 ]; then
          echo "##############################################################"
          echo "#               VULNERABILIDADES CRÍTICAS ENCONTRADAS        #"
          echo "#   Pipeline abortado por questões de segurança!             #"
          echo "##############################################################"
          echo "Relatório completo:"
          cat trivy-report.txt
          exit 1
        else
          echo "✅ Scan de segurança aprovado. Nenhuma vulnerabilidade crítica encontrada."
        fi
    when:
      event: [push, tag]

  - name: OWASP Dependency Check
    commands:
      - mkdir -p reports/dependency-check
      - dependency-check --project "calculadora-api" --scan . --format HTML --format JSON --out reports/dependency-check
      - |
        # Verificar se há vulnerabilidades de alta severidade
        HIGH_VULNS=$(jq '.dependencies[].vulnerabilities[].severity' reports/dependency-check/dependency-check-report.json | grep -c '"HIGH"\|"CRITICAL"')
        if [ "$HIGH_VULNS" -gt 0 ]; then
          echo "########################################################"
          echo "# VULNERABILIDADES CRÍTICAS ENCONTRADAS: $HIGH_VULNS      #"
          echo "#   Pipeline abortado por questões de segurança        #"
          echo "########################################################"
          exit 1
        else
          echo "✅ Nenhuma vulnerabilidade crítica encontrada nas dependências"
        fi
    when:
      event: [push, pull_request, tag]
    
  - name: E2E Tests (Staging)
    commands:
      - cd tests/e2e
      - npm install cypress mochawesome mochawesome-merge mochawesome-report-generator --save-dev
      - mkdir -p results
      - npx cypress run --config baseUrl=${CYPRESS_BASE_URL} --reporter mochawesome --reporter-options "reportDir=results,overwrite=false,html=false,json=true"
      - npx mochawesome-merge "results/*.json" > results/combined.json
      - npx marge results/combined.json -o results --reportTitle "Cypress Test Report"
      - cp -r results /usr/share/nginx/html/reports/e2e/
    environment:
      CYPRESS_BASE_URL: ${CYPRESS_BASE_URL}
    when:
      event: [push]
      branch: [main]

  # Deploy em Homologação
  - name: Deploy em Homologação
    commands:
       - set -e
       - echo ">>> Verificando segurança antes do deploy..."
      
       # Executa o scan novamente para garantir
       - trivy fs --severity HIGH,CRITICAL --exit-code 1 --no-progress .
      
       - echo ">>> Iniciando deploy para HOMOLOGAÇÃO..."
       - pm2 stop calculadora-api-homolog || true
       - pm2 delete calculadora-api-homolog || true
       - pm2 start src/index.js --name calculadora-api-homolog
      
       # Gera relatório final
       - trivy fs --format json -o reports/trivy-homolog-report.json .
       # Copiar relatório para pasta acessível
       - cp reports/dependency-check/dependency-check-report.html /usr/share/nginx/html/reports/
       - echo ">>> Deploy em Homologação concluído."
    depends_on:
      - Security Scan
    when:
      event:
        - push
      branch:
        - main

  - name: Build Metrics
    commands:
      - apk add curl
      - |
        curl -X POST http://prometheus:9090/api/v1/import/prometheus \
          -d "drone_build_duration_seconds{repo=\"${DRONE_REPO}\", status=\"success\"} $(($(date +%s) - ${DRONE_BUILD_STARTED}))"
    when:
      status: [success, failure]
  
  # Adicionar etapa para expor relatórios
  - name: Publish Security Reports
    commands:
      - echo "Relatórios de segurança disponíveis em http://dashboard.local/reports/"
    when:
      status: [success]


  # --- ETAPA 4: DEPLOY EM PRODUÇÃO (Condicional). ---
  # CONDIÇÃO DE SEGURANÇA: Somente quando um evento de TAG é criado
  - name: Deploy em Produção
    commands:
      - set -e
      - echo "🚀 Verificando segurança antes do deploy em PRODUÇÃO..."
      
      # Scan adicional com regras mais rigorosas
      - trivy fs --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed .
      
      - echo "🚀🚀🚀 INICIANDO DEPLOY PARA PRODUÇÃO 🚀🚀🚀"
      - pm2 stop calculadora-api-prod || true
      - pm2 delete calculadora-api-prod || true
      - pm2 start src/index.js --name calculadora-api-prod
      
      # Gera relatório detalhado
      - trivy fs --format template --template "@contrib/html.tpl" -o reports/trivy-prod-report.html .
      - echo "✅ Deploy em Produção concluído com sucesso."
    depends_on:
      - Security Scan
    when:
      event:
        - tag